from __future__ import annotations

from typing import Protocol

from dual_sleeve_trader.core.models import OrderRecord, SymbolFilters


class ExchangeAdapter(Protocol):
    def get_symbol_filters(self, symbol: str) -> SymbolFilters: ...
    def submit_order(self, order: OrderRecord) -> OrderRecord: ...
    def cancel_order(self, client_order_id: str, symbol: str) -> OrderRecord | None: ...
    def fetch_open_orders(self) -> list[OrderRecord]: ...
